# Generated by Django 3.1.6 on 2021-02-15 09:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=17, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
